sudo: false

cache: cocoapods

language: objective-c

before_install:
    - gem install ios_ci --no-document --quiet
    - gem install cocoapods --no-document --quiet
    - export LANG=en_US.UTF-8
    - brew install ios-sim
    - cd Example

script: ios_ci cedar --source-root $TRAVIS_BUILD_DIR/Example --workspace DTCollectionViewManagerExample.xcworkspace --scheme Tests --build-path Build/Products --configuration Debug
